[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "bc9bb998f79011e5783b6a40010e5c6c86e4a186"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "95c671ea080132ce793edc62fa95ebc608c476b3a7b2958f748f99af18694224"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.aarch64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "6099a3fede6b7c6f997568238faa2f7dc5decc73"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "7ec50ea56464ce6b0e72db6a3c2f35718bdce5fc9bcb23998b3d99d7db1f402c"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "b935d3c915b38fcc5ac7350230597dd41630b4c6"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "202532959bd8ce31567f0dfa98e58c135e8b3bf67895fa7be4f41b45be0c1afd"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "f021c3ee71be737f600a252dbf4bb832e8252ba5"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "cd953bf77253c3c5035026186a647c5b003dcbc2e095174949b8d69478fb5b4d"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.aarch64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a92603d57499a40daf9fbf617341365664f4200a"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "855b6f8dc75fedf1b092df68365652363eac647bec7a7b1e2ee02cde39abaaf6"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.armv6l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d3e9fff257a6389df99df45e8dbec4cf5824f6a"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "0ba1961483b6fbcb9a1242588d88866168c6889d507e94cb4a648d0b24777530"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.armv6l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dab28e5ae61708fd93578bef3823073552ce661b"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "f56e61e3c03812794c09315cacc473aad5d80b9653af20f56c933c0496b691ba"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74fe5fc2ef30991621ac98938ef7e7f7a7e4e880"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "1f730d5d483e670b723e5dbdb09b054664944a1c18779b2583a4bea8cba7689b"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "f991509f29efe3f8a99cd328b3405c52a8e111ef"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "366cfd2000b3492c1b901ad5bcc0ecf000e31d5f408deb3ff693202859575ecd"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "b714c6a233d0f1e4cbfcdc34c82a3ca00d54c411"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "81e0732dde5525fa60ee7f6a89c89a170d3446216beb8f2d2030298ba5bf2dbd"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "b5c9e0906ee4f0fd159da494fa9bc71917874904"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "50ada838ceb5cdebe69896b216983842a35eb260e923fd74ba0e4675f893f02a"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "75fc466b7294eb141ca7252317e7a54c9c2c1194"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "4c31aad886156b99ef22683ad7b7a6c994c4dc5fd7bfaae7994f4266f1766dd8"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "riscv64"
git-tree-sha1 = "dcf198b808b9df5818471dbe8bb0251c1ae9916f"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "4429d29bd53e47285227dd0f076daaad559590469288558433dd267ba72ac04d"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.riscv64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "f4a8c5898ed2ae9d555f36b268a269b8ae09b53d"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "f4be50aad13e7058de75ceca72f7a13ed361971d759c6e552afdce4a9028be43"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.x86_64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "c21854316d4844b1ba0b9fc8dbd569ca116f8b19"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "a24701e37cfc3779cec2a4ec2ddb9e28ec125e80f35d2791f3f2868f5e47b349"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "6d23376b58f55730d674181c3d2a9cf87cfb2097"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d91e0f949d830f2b59c3d8751acf232853aa74b0d7f27f3d2f5e352954a812cb"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "bd2cabc31759e6388f9c76cdb017d4a2c5620e45"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "1bb51eec4866e64b71d9657e0b43be7201723093923b5227cfb31653e2e67228"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.x86_64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "70d649d1599a152c00a4714d4fc620bb3c680f62"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "043e94799109e24df200f880791d60dca7cae11790f42aa6c290af8cc5269171"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.3+0/JpegTurbo.v3.1.3.x86_64-w64-mingw32.tar.gz"
