[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "49f7b99f4b67f821eb3979709e115f0595309cc5"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "d7b7940e4b2c1c0643bd323c3e1c0668df9c935514d63ee614ba50458a596312"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.aarch64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "22e9a1bbddd68c578ba2299c4beb497f0df928fe"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "f86877b66a9ea583d519d2acbf67a51c2ee97a9c3d5ef6d1b30f790d7238bcb9"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "f5e3fc700295b7b4379000866351c02da4d27e87"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "08a31aecef67f4b6b16e42af4a214954bc9ca95adece8a1c0b357c18bb623e1a"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "d25dc04a7005a5443844371685d76613d1b57b8e"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "8248ff4d98e2cfe936cbf98a4772d7b1b06575089c12ccc5c09674042dcadcd8"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.aarch64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb55491c7f9f5e0037fa394273cbdd2099d11c78"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "1d04c7bd71f2a7ee30200c91e9791e530390ce5d1e71ef35b5533eaf8057ecdb"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.armv6l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "44f17b5c5b9cbd5be2e8f0eceef9b1fc12da4bf9"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "396ce9e351f9134ed415b87efe1f00de8344d1f72e200c4238194e75132bbeb8"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.armv6l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4670f393c25fdb7740267effc7c3d3d817af542e"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "cb10aeb923dacfc80f7a79eeb90251aaa216df5cd36569114290e263c2dcca64"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7383379827ca290a30469f438be4ce74109dd62a"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "f1532e475eeb6b260e5476b958fc1bdd425111ff4dfd8908ca93f39ed6636afa"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "131e95f649cee4f98ae1555e7bc9f383f89e4464"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "b3c9ee8b0a979611b78174f00b743e5932885652777690b1ca2bf81e416254ea"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "bb6a209e600d6e56ce32805aa4f49c589fac5d5e"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "91121fa12cd1d5b2eb2cddbab0f514920d8628359775869998aa243ab1bcf696"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "71d313c2b8a32bb8aeaad5d9b44c5745c1c3e519"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "4745885e73c3dd4895b7540ee4e9fbb3600ef72f1aef0975e54835aedcbe839b"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "a3462c117a3faa49c0728fe1353224a78629f2e4"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "28e3d2f6c443106d78196995a5549c1765d7303ce65a7023050232dbad085711"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "cbcd2bc73d2e8daffff299d0e59d551cc9e90d76"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "4c4b004bc7114b8b1840ec27bc8d930cf3ac98330091b784369db7c7c121c3f1"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.x86_64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "71f3593804fb3a115f7fcb71b20c4e1f9b32290f"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "a28bc2735186a10be6ab7dea3e83019033c49b4d18314f7f4bdc71eed1d7f31e"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "b0e9d7a2042e588fb3db20b9274d348f7da490c1"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "4dd5314104068cac79a883019a8a0652e8be98d076ff15d6237d8f6fe7a30917"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "aa8002867076606869d628558cd2ee62f99f1672"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "56807fb321e895f773bf042348274b3e204ee57274836b2c7e985c000143b022"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.x86_64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "c7124809a90d597e486fb6f123746eab68992392"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "14e4f2ecfc4949975314f3f85191e638442f1d82cc3cccc8d7bf033836f6aa44"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.4+0/JpegTurbo.v3.0.4.x86_64-w64-mingw32.tar.gz"
