[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "8159e59a156e0fca1664dc2daa3a3b7b7a0b18e3"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d5da114d244027c08f59614ca47370acbeaa701ea248bc392f99a827ad329467"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "9aab8ea8bc281f55f2ae56447e4d0db60fad5492"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "038724ef120f4999b096ac41859f42e0f8fe8ad29d1f3027a3d1243423e0253c"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
git-tree-sha1 = "22f478b30424fdf1001f420b1d3045dffcb924b1"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "29efdaa694f24b0c62f3c74b009a6a7d99209716f33b63ae40794fdbf8006580"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
git-tree-sha1 = "3502746b67d791bf47e26d699332cc3d7d38a7b0"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "f211c860b3197324f936492bb2b27e58457ea9e717d20ce9c37e2f48fda7915f"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "3b81971815b23e03857348c2d153f89bfae6a7ac"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "f35d3cfd937c17379174745b5d2be68c3bf9c8fb003737858ad30464b0c8d1c9"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "74b8834f10e139c4399f33f694808f49fec2491f"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "046649a512da32a8d9a2926523d7d4ec7a2dec43fa238a5eff48fcaf8f110342"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "5ab68c3a650db10ae08401a1d5e1b2535d9a6dcf"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "72935e5d96e497fbcc91672b1b7a4be6d870f73b5663f1cc9c2a38fe99d594c9"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "7daa80f780fe80f9d0c898f0aba8fad014c7ba85"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "e8b961ba9cc06011254f15d31f7ee4df17aa6eb6279f7cbf83a3d8dfa3110f9b"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "b7aadf35fc557efb5c3ac7c88d340ee585555baa"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "0775c5b59d1e976cc66a0261dc41fb9d3e3680aa16a92dc99fff24261df477b1"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.x86_64-apple-darwin14.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "e82fa7eef60ec4feb350f5ea2732ffb5b32b9a51"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "8ac4ef6e0751a06d9aa8240c919039834fe831e83fce7e1561110926acf80c41"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "7c20f31fbb608feec71019a7038f9dc60a1d04ef"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "c95f2afc5ac1ad9c864c50b0eba72850840e434205dc4096f1e8681b787cfcfa"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "432cd3aa484cbc020dee1cbf9b2cdd9d9ad4d75b"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "845ce724e413ed61f3b39fbad4c10f5c449e902e8760f557a069efe1ece06b7f"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.x86_64-unknown-freebsd11.1.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "3fc98eb6c7f851c306dfcb9edbcea79736076a46"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "c5c94d9e0ae760d2d3df38f0f13be60113acf32a0828a601878288f36ed7766c"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.0.1+1/JpegTurbo.v2.0.1.x86_64-w64-mingw32.tar.gz"
