[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "9472204d25ab69d52d571b650fdc9d562455ca4a"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "abdb68ca721a935b4e5ea4e74d4befc50ea961a45d7522f6fcb81510fa3ff582"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.aarch64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "ad40d3fc54a41ff1e9839b4403438b568698675b"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "ab5373e4c8d9fef29699650d3480d483f95ff36597f09a3e4f587a09d473c50a"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "bb6dc815dc592563590e5ce171c77f3a72221e49"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "fddcea596a7a85364f0e10d7be4d43ab81232a810d5519a70327de1da61b6b97"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a4417dee27a10b5cc827633089d5736dfc0cc5b2"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d0ddaa3f805321cb4ae1235dfa9e258d29cd551c41b14259ffa31199212c1aa9"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.armv6l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "946dcdbc788ac6d47198964002253529c04fa27c"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "edb9f782e8bc3521903eed0407f8352433cad13929cd8501e154a9601b6c4436"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.armv6l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f1d3da8b2a226ac0495fde18d161ba344ad06927"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "a6640312ba70021bccb67acc97cf322ba2274f0fcf704606caa324559bdd79a7"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b964b328f5aa4a82cbe0375358e77a674162cdd9"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "0b661ccab72d09c9251b75d6b9a5580213dc44ad90be2fefba61642d6c540b53"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "89b9b26d443d36b6888c38b14e69d80f506afed2"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "2e66b302f51a92557f953bd53f71b244bba7f6bddc7f1c1bd9e91869a8eada51"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "da50ae40654794002ecc5e1372647a4dc07ee26c"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "5140907688be2396a0e72fb748fb677eb80a5dbbe68d82e06292d24745f3065a"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "93e54dd99d92d38ca8c70b84955e194b69ba93e9"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "139a95fffa00c7e70a85a65efff0deadc93bc3641b11b80cc04e0254cbeed5d5"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "9b370687eecca2fa2f1d7371c32501bf94fed247"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d45e18c722f08b4acc20a7fb07e696d1dbbc077ee476921da366cc377d33fd88"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "90586b86f5f29bee29cba8bf165c9958683e4496"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "0e34fae983adcfc7760a2d88a441ac81193064cbfdb81c8e57098d2a0d80eae4"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.x86_64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "22a0f38792d33b65e35189101e60e1fab0a56030"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "26786fb11c394cbac63942312a0621c600826b2c00b43ca6b801fdf6f1b1d7b4"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "ac1bf41d747c31c0d09aa040149c51279c01c43a"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "e30c1476664704de8b53345ea2f43af89539a69ecbb7a2cadcbd903b47a36aaf"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "593a00f2891f36dfa7dc3f543f507f5a207ab348"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "63fb9d257c5a70cac2c506a3d0e876f7dc6414f8397c14efbf2c9faefbd68c9f"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.x86_64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "ac8a1c48a02b397f6ce1beb6473de8bbb3b1e0ce"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "62f64594f0bb42fb2c533bfd86f36c8b82f61bfea50e68a3abfbf23291da12ab"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v2.1.91+0/JpegTurbo.v2.1.91.x86_64-w64-mingw32.tar.gz"
