[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "b80d54484d815d1ace4cb475d53da633579d7d92"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "3b7c4a77ce40f12d256d29a349ff91d01b16f4691c671771b7551121e0a92214"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.aarch64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "a08c2dfa1141fe8d7da04811d61e9f895bbbcbd4"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "696b063dd840469a590a05d227cdcdf1ca700317e104be37e51a97f89a6c180a"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "4d6c83d631a880afdf255959d7d0cfdfec795d01"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "e27185b77311c54ea574fa34b9435d132fa4362bc83b0f3a7837e3c6af1e8723"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a3050fdc930f1784aa63d74d6ea55fcec1deff7"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "b457a5b355d2bf6e6adea4e6b815c5ecb82dedf49fac494503043eaebbdf6226"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.armv6l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2242a7b34afdb4ae97a4cec4bfe2075d1141d840"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "df9aa7001c69a249399361a9fc78f0379398a691728b913124d88446c0888e33"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.armv6l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08c39265c39ea3566d8348098c25c8d9c4426dbd"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "c2520c42b9b485540aecaad18bddf886b905c22743a99ed603e2af04fb5ef173"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c05cd5a073cd1a94efa313d02dde4172100b7393"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "822538f00e05206a40604631ec75f89fc08780b0990bce153363030fc59c764f"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "efe6ec37cf330c3518e5a73ecba6640ff30d8977"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d7c4ebfd0ea985e2a1a4994702dc65e1ca458393e88bc44713cad7182a3ee60d"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "c4d7f651509c0c768ac0d3807cea869cb714a3b0"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "41cd4bda6419c344f0ff85f8256366f37e2d1eb4a3826bd09b23a4ab1fefa2f3"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "d793574f10ae8a3e0d6f1c8e7e8ac83f2468f5c8"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "328dd8275ab17158fc94e5de5cb9a451d85603c792e6ac34cecb8677a106e1a7"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "5ac5e24391b01a196f71b3f637eaaac486e5c446"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "f5c7c242a446900cfeaa32e7648c1ead2710e417ca2355b076a312f837d1f331"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "bafe3cd52ce2d05cf3aade22f2290fc0d3841de8"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "e26f0062321849cbb090d68bdb01ee433bb1316441a2103940ac8b55e77ee5f9"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.x86_64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "4d81e504490cf1152c6945d6d52e6cd5498543bf"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d619b894958b93f3d8ca0c28fa10d1fcdb1f052ea8f09c16d93aff7e5ffe9b05"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "058542cfbdce8d5caf035bc46a6684fdcd6a2cdd"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "18aa05485104dd9fd60e430cb6ba3e68a841f58a73e97d7af33d55177443960e"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "1ae2e3552e52f66d07133d8d19f9b4aa7518cf47"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "4676c6bb21ecab54d2756c664c05814beccd8b0ab5df3c136769fc1f0c7b39af"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.x86_64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "90afa5d4f54d0765f1425728e21d776f6215ee5d"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "958adad2ec510d5aab2b4874991c485ef782b27933db0c4756b4055d24c12a2b"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.1+0/JpegTurbo.v3.0.1.x86_64-w64-mingw32.tar.gz"
