[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "cbb6eced8d272857fd09e108f5af407afb829d0f"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "816e0784bf21d767a987b8d2074abf83597047b770fe7787cbea147940826fff"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.aarch64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "bdf586176535842717dc65c50e43d7e576e4522e"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "7eae470a04f4cd32190e4eee56273efd3f7c152e8b6402abb8a411b7a7e24cf1"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "9095430f5f74afcdb241ff4a301a29227a36c573"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "5b0f0720edc9b035e8f3a6fd8a7da2dc1430769e387b333287880e9bad4f73a8"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "8fdb970f17b1e9dc504c21cd0fc3223fb8813c83"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "ddbe3f86305fa43dbec36e2a6c37ef6bb9e4d7abe10d50555711c7d13265f9b8"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.aarch64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "de8e160cd7c32fd95710fd4157f6a83615cedb57"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "0b16ed82f5f3d584734a4ee4bba0eed20fc2254e0f8f7cbd5e0bee72e40b813c"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.armv6l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "deb3f56cb5f682b8958d664bd7c8f51c5a5b58bb"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "f364fedc91cbfc29eb586effdcfcbed66272083a2feff36077e774cc61fb951e"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.armv6l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d5d43863312652967afc317a15004f51e39cae4a"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "c9a1b067a4393c57a5e47a47e557a3bea784ac41e61498f2ee6c9ac8fdcbbc31"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "131b91d1d8efb3080fe1fd4b51b1c7216f9d4104"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d1cd4aa233bb34429b05eed2ecfa160a8bcac0832d4d7e6e7eaacdf732596d7e"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "9043890af834b3a5067a2a5b95954933df3615c6"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "e4e73bcdc2653d5d1d0a8de8a61ec607d74052e0a3774e150a115ce12c3f0859"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "debbf19badf60847f314494f01cd52add98213db"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "c26b55a5abb1c7cd164a3d6a0e28b473483f0d2f268fe7c0a93c997c4091ef05"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "2d284e98eac7ac4867f1319bb287145699aceec7"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "53bc87c1871a2445c9260f64cabb50c68bdea3320e5f7063f5a3e18a1381b6a1"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "fb51755eb22bad23baa38e801f4719857a32aabc"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "224e8c128197437010f2b4e231ec983707adec28179d44df5f5d48abc4dd801d"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "riscv64"
git-tree-sha1 = "d5e1a7627f0424106ef83da3b243110d92c9948d"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "6806678dc1df5c75f81abf8e1369029bcb3eb8adfb1f6bd46ab157e7464f5681"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.riscv64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "6fc3041bc47a490e740231ac023c4a9011632be2"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "9e7326ff6a6a0f76162da536b26f861fc39aaa3f0f45248af9d501ad036c9b6c"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.x86_64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "3ab5f2c6b84a9cc2bbd5c20bb8f5e76e7f13e1ed"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "970883d99924f57e42db636e88d94db35888572fa8af87dc7e2a041a7cb6156d"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "5631ded12b3e09a28b4cd4f855c2c5f028c28f53"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "21062f04c4282e40ea294f38093d34459bc6495ad31b4a36433d848506546447"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "88527248e22430d57fc7c44b173778499076304c"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "fa927947cb8949b98e1c4a5e825081d9e6f58b664c77703ba0fa3162815d0605"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.x86_64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "dcf40d7a9d26889efcb6a446b44bde1e68e7497f"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "dd902a91c5e575ee186c7a17ec5b4bf066082a2b7238c702af76e4db0e909388"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.2+0/JpegTurbo.v3.1.2.x86_64-w64-mingw32.tar.gz"
