[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "6b104f71c6fc2280dea4cd195cb6800737e8c9aa"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "69f057f1754117cda974e858aafd58e73255da2d3b9dcede3ae1671862bd49b9"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.aarch64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "53efc88989b6919a4ab0eb9137b6dd37d4f02a81"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "7a35f2bb5209e416381210739319be56d8dc52ab934de0f925ca574a649f7fb7"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "cf330c13af10b5be4a7523d5b207c5a63989b588"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d19bc05186d907597d432d24ab0662dfcbeb842e830bb52aef0380943dffdb06"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7309287b57c5777f50af951a1b030c5a6a75272f"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "552174b58a17b28d992e7ad9f07769ee7c7c9da6cff4984527744904e0916fab"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.armv6l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fcd569ae1fc939e5a43da734a287a0ecba6f46a6"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "16353955bb21089399f61086761fd1f896300b1dccd80612c068b894f47a6e14"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.armv6l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07ed0cd4cf82e8dc8dae64de7e76d0cc5d3cd55a"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "bb659fa0f3b5b7701e4f8d9f68ba2af39c2d41b2a17ae0bf9894cb5e1089a3ba"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d338258bd9653668fe0571c53862a716242ce115"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "d2c79410040591e563a239e2dbb1368f1d5fbc30394c9644fed284a7b2653d29"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "c249b0a03c141b523f46280f72dbdaeab77b9c4d"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "3b41c8a5119017fa1950536d84cc73a821b3b99cbb0a89f1b1ab829c8fc78c38"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "4ab5751ffad829e97ab3871fd8663fc7abce95f2"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "b8aec50b31f7135a689944ded507f0737667af3e0f38f3599f91f5c71c9510b9"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "97df6f9bd565039e1df848e15f671579ce9c4786"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "72d19f4c46e0f09280455814c7530cc020064131d9f8db1fc9601e1fa148d4e7"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "965cd4d115e974811205ada61daaf392d1e7e202"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "84f5774b8a342847ded8da472131fa4160601181f5c4c37641ce8ffd5df8a5a3"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "60b6e54f05c35fd3fb7fad2255501d7769bc963c"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "930630daf17e56ab26bd46371b4dde34733160a6152ca45f61358a59026f4893"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.x86_64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "1b82967d82b35f8abcf39b837402df5ffbde6a09"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "a1683862160b612a81eae366bafb8a717dc5b35349eb2a304b6289fbbbd57cf6"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "58d44486dd5249781e46c8009a8d236613430932"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "13ebabe005d6eb9bf7590be5b4f46bbe9fb79fc6e82c2190b2bb1145da67b9c4"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "98f9fdbdc5132f1526b993fe34c70f0e6f514eb6"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "31d7108181d53629a8a63bb49489d569eb7fe5f38c10847b7fcc180e1184563b"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.x86_64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "3d45235174db770e39e4bd4712c174505d5821dc"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "ddd764c55cb266bbf2f63366e9f79e86c9f6c9a0f22c60ee2dfefa73b7c33770"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.0.3+0/JpegTurbo.v3.0.3.x86_64-w64-mingw32.tar.gz"
