[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "0256eb1bc32b9b7444ed202570fad8b2a2cd86e6"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "33c4cf22d921d2d3ec993a60162d048a0f91c1f53cbeffb4b55ade3a6095f6f4"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.aarch64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "cc087cc7929c12d2d5364613404429f3ad76068f"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "b321d97eee4a64b33803cfd7a9cdfdcd0e15ab7d44b66cc2941ad341ce7e1306"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.aarch64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "26f5be9ef0ad8725ae5fe584cdb523f459021db2"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "705515c13558c5f9cbca58bbd3b6f00c0d4115fdcd4eb5c637ccb27a090cdb51"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.aarch64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "aarch64"
git-tree-sha1 = "6a2927bcd3e13615de4126edf0ec6c27924ccd0c"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "2629d1f7edaafc4471844b8c53eecff08f0c458461e17311be0738d45094e2f5"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.aarch64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7f4bbb60a48ae6e6495b6258a840980f563440b"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "451039135583ff2e6478c82848d28782141face78a9c186e58237ff0802f696e"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.armv6l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "740e76ebc25f99fc7f444c6d3eb57be150c54038"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "951a6c910128cbdf174bf50c85cafc4770dfbedd8ed2cc896762a02817d8b725"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.armv6l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2dea9f13c2509094b462f1ad4b9676dc342b4f8c"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "4d6cecbd4080500bad3dba2de0022f4645dd235911524ce41d1c2c70cd5a2954"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.armv7l-linux-gnueabihf.tar.gz"
[[JpegTurbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1938a9878db613856ba7dffb335325c4eea2397e"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "051dd585874c537143881b173ed4f1d27e41034a9e49caf6aa724e83f8659103"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.armv7l-linux-musleabihf.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "d59c38516d72a09cb179c04ff4708482705c59ed"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "c3a973affd2452d58f36dbc65c1e834e36cb65704b4d48eab973e6f762d4a9ad"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.i686-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "0345fe59057659140ae060e5e0f391ec9e9fe0b8"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "e9b7a34c33c81a1b57b2d3dced902ca8b34d4e4f81eb7eff37d3a830a6bcf87b"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.i686-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "i686"
git-tree-sha1 = "f22d656545ec92f289db749a5af6e156fafb4ec8"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "67b124b1078c02e655c7f4a33d1fe8f71d7d6beaa4d1aa43d420d82e2e838979"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.i686-w64-mingw32.tar.gz"
[[JpegTurbo]]
arch = "powerpc64le"
git-tree-sha1 = "4eda047d868d01669ded26adfa1cabedf6e3767c"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "9a4e7ee1e12340bc15d99a74d1fb7f691c50068484d1dfd2ad5eb772a03361b1"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.powerpc64le-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "d5d47b71e041f5e9734620599b06804bc0cfa54b"
os = "macos"

    [[JpegTurbo.download]]
    sha256 = "f475f7da4ba2fd868730660b97d6fad9e597fccc6588af9d644075414d8c6836"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.x86_64-apple-darwin.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "cb11dc93c1c43dfb18210a9037d1329d5497cbf1"
libc = "glibc"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "ee4a5cf3e4450fd6b4e8f63a8f51d5a81b8e20c1a378ce5cfdf22c65058c34b3"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.x86_64-linux-gnu.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "77dc5b2148621ba90fc4946fd090690e5b4a1b04"
libc = "musl"
os = "linux"

    [[JpegTurbo.download]]
    sha256 = "590e0d99639c461005100e569edc9ae19ba62e882d5367f5127ca630b9fab6b8"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.x86_64-linux-musl.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "8a876fbd66214dca789f2e853e2e75bbbdc149cb"
os = "freebsd"

    [[JpegTurbo.download]]
    sha256 = "cd345f969790cf0fa97ac45e9d16161f706c8c4316065d93df205656e9c7e272"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.x86_64-unknown-freebsd.tar.gz"
[[JpegTurbo]]
arch = "x86_64"
git-tree-sha1 = "c9337de24d0273ba51df5a896d276f87e5c75cec"
os = "windows"

    [[JpegTurbo.download]]
    sha256 = "f9f5e013899d7b49f91a937d669412f5f1f4791a72da449f1c70feb226d03ab1"
    url = "https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl/releases/download/JpegTurbo-v3.1.0+0/JpegTurbo.v3.1.0.x86_64-w64-mingw32.tar.gz"
